module.exports = {
    CollapsibleElement  : require('./CollapsibleElement'),
    ColorPicker         : require('./ColorPicker'),
    CompositeControl    : require('./CompositeControl'),
    ContentEditable     : require('./ContentEditable'),
    CoordinateControl   : require('./CoordinateControl'),
    Equalizer           : require('./Equalizer'),
    Factory             : require('./Factory'),
    FloatImageControl   : require('./FloatImageControl'),
    LightProperties     : require('./LightProperties'),
    LookupTable         : require('./LookupTable'),
    MultiViewControl    : require('./MultiViewControl'),
    NumberInput         : require('./NumberInput'),
    NumberSliderControl : require('./NumberSliderControl'),
    ParameterSet        : require('./ParameterSet'),
    PixelOperatorControl: require('./PixelOperatorControl'),
    ProbeControl        : require('./ProbeControl'),
    TextInput           : require('./TextInput'),
    VolumeControl       : require('./VolumeControl'),
};
